CREATE TABLE `company_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(255),
	`cnpj` varchar(20),
	`priceRegion` enum('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO') NOT NULL DEFAULT 'SP',
	`taxaLeisSociais` decimal(6,2) NOT NULL DEFAULT '128.23',
	`bdiPercentual` decimal(6,2) NOT NULL DEFAULT '25.00',
	`lucroPercentual` decimal(6,2) NOT NULL DEFAULT '8.00',
	`issPercentual` decimal(6,2) NOT NULL DEFAULT '5.00',
	`pisPercentual` decimal(6,2) NOT NULL DEFAULT '0.65',
	`cofinsPercentual` decimal(6,2) NOT NULL DEFAULT '3.00',
	`irpjPercentual` decimal(6,2) NOT NULL DEFAULT '1.20',
	`csllPercentual` decimal(6,2) NOT NULL DEFAULT '1.08',
	`adminCentralPercentual` decimal(6,2) NOT NULL DEFAULT '4.00',
	`despesasFinanceirasPercentual` decimal(6,2) NOT NULL DEFAULT '1.00',
	`riscosPercentual` decimal(6,2) NOT NULL DEFAULT '1.00',
	`regimeTributario` enum('simples_nacional','lucro_presumido','lucro_real') NOT NULL DEFAULT 'lucro_presumido',
	`dataReferenciaPrecos` varchar(10) DEFAULT '2025/01',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `company_settings_userId_unique` UNIQUE(`userId`)
);
